config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    root 'home#index'

    resources :home do 
        get 'switch',on: :collection  
        get 'reset_all', on: :collection
        get 'pre_reset', on: :collection
        get 'add_hours', on: :member

        get 'pre_change_name', on: :member
        post :change_name, on: :member

        get 'pre_change_phone', on: :member
        post 'change_phone', on: :member

        get 'pre_change_time', on: :member
        post 'change_time', on: :member

        post 'populate', on: :collection
    end
    
end

app/models/assassin.rb
class Assassin < ActiveRecord::Base
    
    def time_left
        # Default time to complete assignment is 24 hours
        (24.0-(Time.new - last_kill)/(60*60)).round(3)    
    end
    
    def self.activeAssassins(total)
        return Assassin.first(total)
    end
    
    def self.findPrevious(id)
        currentID = Assassin.updateID(id)
        all = Assassin.all
        while true
            killed = Assassin.find(currentID).killed.to_i
            if(killed == 0) 
                break
            end
            currentID = Assassin.updateID(currentID)
        end
        return Assassin.find(currentID.to_i)
    end
    
    def self.updateID(id)
        result = 0
        if id.to_i == 1
            result = Assassin.all.length
        else 
            result = id.to_i - 1
        end
        return result.to_i
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @len = Assassin.all.length.to_i
        @all = Assassin.activeAssassins(@len)  
        @numAlive = Assassin.where(:killed => 0).length.to_s
    end
    
    def populate 
        len = Assassin.all.length
        if len == 0
            # Harcoded list of names
            names = ["Max Drimmer", "Kyle Robinson", "Clare Moffatt", "Thomas Liu", "Hannah Levy", "Anna Thomas", "Anjali", "Regina Nguyen", "Mario Khosla", "Rebecca Triplett", "Tarek Abdelghany", "Jason Randoing", "Katie Schneider", "Derek Phillips", "Kathleen Miller", "Otto Zhen", "Bilaal Rajan",  "Ibrahim Bharmal", "Sarah Radzihovsky", "Blaire Hunter", "Tiffany Kuo", "Kyle D'Souza", "Arturo Rojas", "Katie Keyser", "Joshua Kravitz", "A.J", "Albert Feng", "Elisa Hofmeister", "Rochelle Rouhani", "Richie Hojel", "Matthew Stuart", "Kevin Chavez", "Ali Eicher", "Jack Seaton", "Shawn Fenerin", "James Webb", "Kais Ben Halim", "Alexandra Nguyen-Phuc", "Alex Chanthavong", "Hayley Ritterhern", "Kaylee Johnson", "Lauren Norheim", "Patrick Conaton", "Krista Chew", "Brennan Shacklett", "Gigi Nwagbo", "Neel Ramachandran", "Catherina Xu", "Rishab Mehra", "Konner Robison", "Tyler Dammann", "Brandon Racca", "Sam Premutico", "Jack Herrera", "Souraya Karimi", "Geoff Angus", "Simba", "Julia Doody", "Nathan Petrie"]
            
            # Hardcoded list of corresponding numbers. 
            # Example: the phone number of the first name (index = 0) in the names array
            # is the first number (index = 0) in the numbers array
            numbers = ["(972) 415-8553", "(617) 234-9738", "(321) 998-2131", "(972) 415-8553", "(531) 782-7767", "(817) 222-2912", "(972) 415-8553", "(321) 998-2131", "(531) 782-7767", "(972) 415-8553", "(671) 131-2131", "(817) 222-2912", "(972) 415-8553", "(617) 234-9738", "(531) 782-7767", "(617) 234-9738", "(424) 321-3665",  "(981) 122-3343", "(972) 415-8553", "(424) 321-3665", "(817) 222-2912", "(671) 131-2131", "(972) 415-8553", "(424) 321-3665", "(424) 321-3665", "(817) 222-2912", "(321) 998-2131", "(972) 415-8553", "(531) 782-7767", "(671) 131-2131", "(817) 222-2912", "(981) 122-3343", "(424) 321-3665", "(817) 222-2912", "(671) 131-2131", "(424) 321-3665", "(321) 998-2131", "(617) 234-9738", "(321) 998-2131", "(817) 222-2912", "(424) 321-3665", "(617) 234-9738", "(817) 222-2912", "(981) 122-3343", "(617) 234-9738", "(531) 782-7767", "(321) 998-2131", "(617) 234-9738", "(972) 415-8553", "(981) 122-3343", "(424) 321-3665", "(972) 415-8553", "(531) 782-7767", "(671) 131-2131", "(671) 131-1322", "(617) 234-9738", "(531) 782-7767", "(321) 998-2131", "(972) 415-8553"]
            
            resultHash = {}
            numbersHash = {}
            
            index = 0
            names.each do |member|
                randomNumber = rand(1...99999)
                # Links name with random seed
                resultHash[member] = randomNumber
                
                # Links name with phone number
                numbersHash[member] = numbers[index]
                
                index = index + 1
            end
            
            # Sorts array from lowest seed to highest
            sorted = resultHash.sort_by{|key, value| value}
            
            sorted.each do |key, value|
                assassin = Assassin.new()
                assassin.name = key.to_s
                assassin.seed = value.to_i
                assassin.killed = 0
                assassin.last_kill = Time.new
                assassin.phone = numbersHash[key.to_s]
                assassin.save(:validate => false)
            end
        end
        redirect_to :controller => :home, :action => :index
    end
    
    def switch
        query = params[:query].downcase
        assassinID = params[:id]
        previous = Assassin.findPrevious(assassinID)
        assassin = Assassin.find(assassinID)
        result = ""
        if query == "revive"
            assassin.killed = 0
            result = "assassinate"    
        else 
            previous.last_kill = Time.new
            assassin.killed = 1
            result = "revive"
        end
        assassin.last_kill = Time.new
        assassin.save(:validate => false)
        previous.save(:validate => false)
        render :text => result   
    end
    
    def reset_all
        allPlayers = Assassin.all
        allPlayers.each do |player|
            player.last_kill = Time.new
            player.save(:validate => false)
        end
        redirect_to :controller => :home, :action => :index
    end
    
    def add_hours
        allPlayers = Assassin.all
        id = params[:id]
        allPlayers.each do |player|
            player.last_kill =  player.last_kill + id.to_i.hours
            player.save(:validate => false)
        end
        redirect_to :controller => :home, :action => :index
    end
    
    def pre_change_name
        id = params[:id]
        @assassin = Assassin.find(id)
    end
    
    def change_name
        id = params[:id]
        @assassin = Assassin.find(id)
        @assassin.name = params[:assassin][:name]
        @assassin.save(:validate => false)
        redirect_to :controller => :home, :action => :index
    end
    
    def pre_change_phone
        id = params[:id]
        @assassin = Assassin.find(id)
    end
    
    def change_phone
        id = params[:id]
        @assassin = Assassin.find(id)
        @assassin.phone = params[:assassin][:phone]
        @assassin.save(:validate => false)
        redirect_to :controller => :home, :action => :index
    end
    
    def pre_change_time
        id = params[:id]
        @assassin = Assassin.find(id)
    end
    
    def change_time
        id = params[:id]
        @assassin = Assassin.find(id)
        difference = (params[:time].to_f - @assassin.time_left.to_f).round(3)
        final_time = @assassin.last_kill + difference.hours
        @assassin.last_kill = final_time
        @assassin.save(:validate => false)
        redirect_to :controller => :home, :action => :index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_assassins.html.erb
<h2  class="text-centered page-header">
    Assassin Assignments: (<%= alive %> Survivors)
</h2>
<div class="row">
    <% count = 1 %>
    <% all.each do |a|%>
        <div class="col-lg-3 col-sm-4">
            <% if a.killed == 0  %>
                <div class="assassin-card assassin-card-active" id="container-<%=count.to_s%>">
                    <h4 class="text-centered id"><%=count.to_s%></h4>
                    <h5 class="text-centered name">
                        <%=a.name.to_s%>
                        <a href="/home/<%=a.id.to_s%>/pre_change_name" class="edit"></a>
                    </h5>
                    <div class="black-box">
                        <h5 class="text-centered hour-header">Hours Left</h5>
                        <h5 class="text-centered">
                            <%= (24.0-(Time.new - a.last_kill)/(60*60)).round(3) %>
                        </h5>
                        <a href="/home/<%=a.id.to_s%>/pre_change_time" class="edit edit-time"></a>
                    </div>
                    <div class="phone-box">
                        <h5 class="text-centered"><%= a.phone %></h5>
                        <a href="/home/<%=a.id.to_s%>/pre_change_phone" class="edit edit-phone">
                        </a>
                    </div>
                    <div class="action-button kill-button" id="action-button-<%=count.to_s%>">Assasinate</div>
                </div>
            <% else %>
                <div class="assassin-card assassin-card-killed" id="container-<%=count.to_s%>">
                    <h4 class="text-centered id id-killed"><%=count.to_s%></h4>
                    <h5 class="text-centered name name-killed"><%=a.name.to_s%></h5>
                    <div class="action-button revive-button" id="action-button-<%=count.to_s%>">Revive</div>
                </div>
            <% end %>
            <script type="text/javascript">
                //<![CDATA[
                    new Switch("action-button-<%=count.to_s%>", "container-<%=count.to_s%>", "<%=a.id%>", "GET", "/home/switch?query=");
                //]]>
            </script>
        </div>
        <% count = count + 1 %>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="container">
    <% if @len == 0 %>
        <%= link_to('Populate', populate_home_index_path, :method => :post,  :class =>"btn btn-primary")%>
    <% else %>
        <%= render(:partial => "assassins", :locals => {:all => @all, :alive => @numAlive})%>
    <% end %>
</div>

app/views/home/pre_change_name.html.erb
<div class="container">
    <h2  class="text-centered page-header">Change Name</h2>
    <div class="row">
        <%= form_for @assassin, method: :post, url: {action: :change_name} do |form| %>  
            <%= form.text_field :name, :placeholder => @assassin.name %> 
            <%= form.submit "Update", :class => "btn btn-primary" %>
        <%end%>
    </div>
</div>
        

app/views/home/pre_change_phone.html.erb
<div class="container">
    <h2  class="text-centered page-header">Change Phone - <%= @assassin.name %></h2>
    <div class="row">
        <%= form_for @assassin, method: :post, url: {action: :change_phone} do |form| %>  
            <%= form.text_field :phone, :placeholder => @assassin.phone %> 
            <%= form.submit "Update", :class => "btn btn-primary" %>
        <%end%>
    </div>
</div>

app/views/home/pre_change_time.html.erb
<div class="container">
    <h2  class="text-centered page-header">Change Time Left - <%= @assassin.name %></h2>
    <div class="row">
        <%= form_tag action: :change_time do |form|%>
            <% time = @assassin.time_left %>
            <h4 class="text-centered blue-text">Current Hours Left: <%=time%></h4>
            <%= text_field_tag 'time' %>
            <%= submit_tag "Update", :class => "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/home/pre_reset.html.erb
<div class="container">
    <h2  class="text-centered page-header">Reset Center</h2>
    <div class="row">
        <div  class="col-lg-6">
            <div class="reset-box">
                <h4 class="text-centered">Set Clock to 24 Hours: All</h4>
                <%= link_to('Reset', reset_all_home_index_path, :class => "btn btn-primary") %>
            </div>
        </div>
        
        <div  class="col-lg-6">
            <div class="reset-box">
                <h4 class="text-centered">Add 6 hours: All</h4>
                <%= link_to('Add Six', {:controller => :home, :action => :add_hours, :id => 6}, :class => "btn btn-primary") %>
            </div>
        </div>
        
        <div class="col-lg-6">
            <div class="reset-box">
                <h4 class="text-centered">Add 2 hours: All</h4>
                <%= link_to('Add Two', {:controller => :home, :action => :add_hours, :id => 2}, :class => "btn btn-primary") %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Assassins</title>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>
        <!-- JQuery Plugin -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>

	    <!-- Latest compiled and minified Bootstrap JavaScript -->
  	    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  	    <!-- Latest compiled and minified Bootstrap CSS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        
        <!-- Switch, Progress JavaScript -->
        <%= javascript_include_tag "switch", "progress" %>
        
        <!-- Progress CSS -->
        <%= stylesheet_link_tag "progress" %>
        
    </head>
    
    <body>
        <div class="navbar navbar-fixed-top navbar-inverse">
			<div class="container-fluid">
				<!-- Title Header -->
				<a href="/home" class="navbar-brand whiteLink">Assassins</a>

				<button class="navbar-toggle" data-toggle="collapse" data-target="#dirk">
                    <span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

				<div class="collapse navbar-collapse navHeaderCollapse" id="dirk">
					<ul class="nav navbar-nav navbar-left">
                        <% if user_signed_in? %>
                            <li>
                        <%= link_to('Reset Center', pre_reset_home_index_path) %>
                            </li>
                            
                            <li>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                            </li>
                            
                        <% else %>
                            <li>
                                <%= link_to('Login', new_user_session_path) %>  
                            </li>
                        <% end %>
					</ul>
				</div>
			</div>
		</div>
        <div class="spacer"></div>
        <% if notice != nil %>
            <div class="notice text-centered"><%= notice %></div>
        <% end %>
        <% if alert != nil %>
            <div class="alert text-centered"><%= alert %></div>
        <% end %>
        
        <%= yield %>
    </body>
</html>